In [1]:
import numpy as np

In [2]:
print('hello_world')

hello_world


In [3]:
myarr = np.array([[3,5,86,78]], np.int64)  #assigning the space by np.int32 ,
#the memory control is in our hands.

In [4]:
#the one bracket means 1-dimensional array, 2x brackets means 2-dimensional array.
#as many brackets that many dimensinal array.

In [5]:
myarr[0,1]

5

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

**adding/changing element in the array**

In [8]:
myarr[0,1] = 12

In [9]:
myarr

array([[ 3, 12, 86, 78]], dtype=int64)

**array creation methods in numpy**

In [10]:
myarr.size

4

In [11]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

**creating a array of zeros**

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng = np.arange(15) #it gives the array from n to n-1

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace = np.linspace(1,5,12) #it gives us the total 12 elements between 1 and 5

In [20]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [21]:
emp = np.empty((4,6))

In [22]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.15710427e-306, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 8.01097889e-307, 1.42417629e-306,
        8.45593934e-307, 6.89805151e-307, 1.42421160e-306],
       [1.06810268e-306, 8.34448108e-308, 1.78022342e-306,
        8.06635958e-308, 1.42410974e-306, 3.20558931e-317]])

In [23]:
emp[0,0] = 2222

In [24]:
emp

array([[2.22200000e+003, 4.67296746e-307, 1.69121096e-306,
        1.15710427e-306, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 8.01097889e-307, 1.42417629e-306,
        8.45593934e-307, 6.89805151e-307, 1.42421160e-306],
       [1.06810268e-306, 8.34448108e-308, 1.78022342e-306,
        8.06635958e-308, 1.42410974e-306, 3.20558931e-317]])

In [25]:
emp_like = np.empty_like(lspace) #created\copy a empty matrix of same size of provided matrix. 

In [26]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [27]:
emp_like[1] = 15

In [28]:
emp_like[0] = 16

In [29]:
emp_like

array([16.        , 15.        ,  1.72727273,  2.09090909,  2.45454545,
        2.81818182,  3.18181818,  3.54545455,  3.90909091,  4.27272727,
        4.63636364,  5.        ])

In [30]:
ide1 = np.identity(45) #created a identity matrix of 45x45 

In [31]:
ide1

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
ide2 = np.identity(2) #created a identity matrix of 2x2

In [33]:
ide2 # i hope that you know ,what is a indentity matrix. 

array([[1., 0.],
       [0., 1.]])

In [34]:
ide2.shape

(2, 2)

In [35]:
ide1.shape

(45, 45)

### matrix reshaping concept

In [36]:
matrix1 = np.arange(99)

In [37]:
matrix1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
matrix1 = matrix1.reshape(3,33) # it reshapes the matrix accroding to your condition.
# we made a 1-D matrix into 2-D matrix.

In [39]:
matrix1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [40]:
matrix1 = matrix1.ravel() # it made it a simple,clear,(in 1-D matrix)

In [41]:
matrix1.shape

(99,)

## Axis concept

**sum of rows&column and create a new matrix of 1-D matrix**

**constructing a 2-D matrix**

In [42]:
array1 = [[1,2,6],[8,5,6],[20,13,14]]

In [43]:
array1

[[1, 2, 6], [8, 5, 6], [20, 13, 14]]

In [44]:
ar = np.array(array1)

In [45]:
ar

array([[ 1,  2,  6],
       [ 8,  5,  6],
       [20, 13, 14]])

In [46]:
ar.sum(axis = 0) #1+8+20=29 , 2+5+13=20 , 6+6+14=26

array([29, 20, 26])

In [47]:
ar.sum(axis = 1) #1+2+6=9 , 8+5+6=19 , 20+13+14=47

array([ 9, 19, 47])

**Talking about some of the function & attributes**

In [48]:
ar.T # this .T transposes the matrix, means it changes the elements from row to coloumn and vice versa. 

array([[ 1,  8, 20],
       [ 2,  5, 13],
       [ 6,  6, 14]])

In [49]:
ar.flat # helps in using iterative statements like for or while loops. 

In [50]:
for item in ar.flat: # we used ar.flat for get iterative .
    print(item)

1
2
6
8
5
6
20
13
14


In [51]:
ar.ndim # shows the number of dimensions

2

In [52]:
ar.size # shows the number of elements.

9

In [53]:
ar.nbytes # show the number of bytes consumed by your array.

36

## Function the finding maximum & minimum value in the given array.

**Creating a 1-D array**

In [54]:
matrix_one = np.array([4,23,65,874,321])

In [55]:
matrix_one.size

5

In [56]:
matrix_one.argmax() # prints the index which is having a max vlaue.
                    # notice the paranthisis after the funtion.
                    # concept of function,methods

3

In [57]:
matrix_one.argmin() # prints the index which is having a min value.

0

**printing the value of the indexes**

In [58]:
print(matrix_one[matrix_one.argmax()])

874


In [59]:
print(matrix_one[matrix_one.argmin()])

4


## function for sorting the array.

**.argsort prints the index of all the elements not the sorted elements.for printing the sorted array you have to use your own brain.**

In [60]:
matrix_one.argsort() # .argsort is a function/method for sorting the matrix.

array([0, 1, 2, 4, 3], dtype=int64)

In [61]:
for items in matrix_one.argsort(): # I used my brain.
    print(matrix_one[items])
    

4
23
65
321
874


In [62]:
ar

array([[ 1,  2,  6],
       [ 8,  5,  6],
       [20, 13, 14]])

## sorting in 2-D array.

## adding/multiplying of two matrixes

In [69]:
ar + array1

array([[ 2,  4, 12],
       [16, 10, 12],
       [40, 26, 28]])

In [70]:
[324,34] + [54,64]

[324, 34, 54, 64]

In [71]:
ar * array1

array([[  1,   4,  36],
       [ 64,  25,  36],
       [400, 169, 196]])

In [74]:
ar.sum()

75

In [75]:
ar.max()

20

In [76]:
ar.min()

1

In [77]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [79]:
ar.argmax(axis=1)

array([2, 0, 0], dtype=int64)

In [80]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [1, 2, 0],
       [1, 2, 0]], dtype=int64)

In [81]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [82]:
np.sqrt(ar) # finds the square root.

array([[1.        , 1.41421356, 2.44948974],
       [2.82842712, 2.23606798, 2.44948974],
       [4.47213595, 3.60555128, 3.74165739]])

In [83]:
np.where(ar>5)

(array([0, 1, 1, 2, 2, 2], dtype=int64),
 array([2, 0, 2, 0, 1, 2], dtype=int64))

In [84]:
np.count_nonzero(ar) # counts the zero

9

In [85]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [86]:
import sys

In [89]:
py_ar = [0,4,55,2] 

In [90]:
np_ar =np.array(py_ar)

In [91]:
sys.getsizeof(1) + len(py_ar)

32

In [92]:
np_ar.itemsize * np_ar.size

16